variables:
  AWS_REGION: "us-east-1"
  AWS_PROFILE: "ohhey"

stages:
  - test
  - push

before_script:
  - apt-get update -y
  - apt-get install default-jre -y
  - curl -O https://download.clojure.org/install/linux-install-1.10.0.442.sh
  - chmod +x linux-install-1.10.0.442.sh
  - ./linux-install-1.10.0.442.sh
  - mkdir ~/.aws
  - echo $AWS_CREDENTIALS | base64 --decode > ~/.aws/credentials
  - cd api
  - AWS_REGION=us-east-1 AWS_PROFILE=ohhey clojure -A:test

test:
  stage: test
  script:
    - bin/kaocha peer

push:
  stage: push
  only:
    - master
  script:
    - git reset --hard HEAD
    - bin/push
