variables:
  AWS_REGION: "us-east-1"
  AWS_PROFILE: "ohhey"

stages:
  - test
  - push

before_script:
  - mkdir ~/.aws
  - echo $AWS_CREDENTIALS | base64 --decode > ~/.aws/credentials
  - cd api
  - AWS_REGION=us-east-1 AWS_PROFILE=ohhey clojure -A:test

test:
  stage: test
  image: clojure:tools-deps
  script:
    - cd api
    - bin/kaocha peer

push:
  stage: push
  image: clojure:tools-deps
  only:
    - master
  script:
    - cd api
    - bin/push
