variables:
  AWS_REGION: "us-east-1"
  AWS_PROFILE: "ohhey"

stages:
  - test
  - push

before_script:
  - mkdir ~/.aws
  - echo $AWS_CREDENTIALS | base64 --decode > ~/.aws/credentials

cache:
  key: deps-cache-v1
  paths:
    - api/.cpcache

test:
  stage: test
  image: clojure:tools-deps
  script:
    - cd api
    # - bin/kaocha peer
    - ./bin/datomic-socks-proxy -p ohhey -r us-east-1 dev &
    - bin/kaocha client

push:
  stage: push
  image: clojure:tools-deps
  only:
    - master
  script:
    - cd api
    - bin/push
