variables:
  DATABASE: "ohhey-test"

before_script:
  - apt-get update -y
  - apt-get install default-jre -y
  - curl -O https://download.clojure.org/install/linux-install-1.10.0.442.sh
  - chmod +x linux-install-1.10.0.442.sh
  - ./linux-install-1.10.0.442.sh
  - cd api
  - clojure -A:test

test:
  script:
    - cd api && bin/kaocha
