version: 2.1

defaults: &defaults
    working_directory: ~/ohhey
    docker:
      - image: ohhey/circleci
    environment: # environment variables for primary container
      AWS_REGION: "us-east-1"
      AWS_PROFILE: "ohhey"
      JVM_OPTS: -Xmx3200m # limit the maximum heap size to prevent out of memory errors

jobs:
  build:
    <<: *defaults
    steps:
      - checkout # check out source code to working directory
      - run: mkdir ~/.aws && echo $AWS_CREDENTIALS | base64 --decode > ~/.aws/credentials
      - restore_cache: # restores saved cache if checksum hasn't changed since the last run
          key: ohhey-deps-{{ checksum "api/deps.edn" }}-{{ checksum "ui/package-lock.json" }}
      # build ui
      - run: cd ui && npm ci && npm run build
      # install api deps
      - run: cd api && clojure -A:test -e ":deps-success"
      - persist_to_workspace:
          root: ~/
          paths:
            - ohhey
            - .aws
            - .m2

      - save_cache: # generate and store cache in the .m2 directory using a key template
          paths:
            - ~/.m2
            - api/.cpcache
            - ui/node_modules
          key: ohhey-deps-{{ checksum "api/deps.edn" }}-{{ checksum "ui/package-lock.json" }}

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: cd api && bin/kaocha peer
      - run: cd ui && npm test

  integration_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: mkdir ~/.ssh
      - run: echo "18.205.2.182 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBKbAYmaMuyqzZ6yShShSMbygTQLVCFwH4wxW9/b5M12Af8Hc7G6i4a6nFa4enBOzg5SftTtyqfl20UmFGKYJVy0=" > ~/.ssh/known_hosts
      - run:
          command: cd api && ./bin/datomic-socks-proxy -p ohhey -r us-east-1 prod
          background: true
      - run: cd api && bin/kaocha client

  push:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: cd api && git status && git reset --hard HEAD && bin/push

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: cd api && bin/deploy $CIRCLE_SHA1
      - run: cd ui && npm run deploy

workflows:
  version: 2
  build_test_push:
    jobs:
      - build
      - test:
          requires:
            - build
      - integration_test:
          requires:
            - build
          filters:
            branches:
              only: master
      - push:
          requires:
            - test
            - integration_test
          filters:
            branches:
              only: master
      - hold:
          type: approval # requires that an in-app button be clicked by an appropriate member of the project to continue.
          requires:
           - push
      - deploy:
          requires:
            - hold
